# -*- coding: utf-8 -*-
"""Exercício 3b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Sz97pZO68s9zstjsz75QUaZDCBjR2P7
"""

n = input('Digite um número inteiro: ')

try:
    print('O digito das dezenas é', (n[-2]))
except IndexError:
    print('O dígito das dezenas é 0')