# -*- coding: utf-8 -*-
"""Exercício 1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11d6kB7Xw5LH7yQE3pABSlZatcfb3ohLv
"""

nome = input('Digite o nome do cliente: ')
dia = input('Digite o dia de vencimento: ')
mes = input('Digite o mês de vencimento: ')
valor = input('Digite o valor da fatura: ')

print('Olá,', nome)
print('A sua fatura com vencimento em', dia, 'de', mes, 'no valor de R$', valor, 'está fechada.')