# -*- coding: utf-8 -*-
"""Exercício 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CfdEH9_QFhT57PQuPDyFtziulomp_Abr
"""

n1 = int(input('Digite a primeira nota: '))
n2 = int(input('Digite a segunda nota: '))
n3 = int(input('Digite a terceira nota: '))
n4 = int(input('Digite a quarta nota: '))

media = (n1+n2+n3+n4)/4

print('A média aritmética é', media)