# -*- coding: utf-8 -*-
"""Exercício 2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX-tWTAi8Suvw87fnFh69r3behJy_inv
"""

segundos = int(input('Por favor, entre com o número de segundos que deseja converter: '))

segundos_restantes = segundos%60
min = segundos//60
minutos_restantes = min%60
horas = min//60
horas_restantes = horas%24
dias = horas//24

print(dias, 'dias,', horas_restantes, 'horas,', minutos_restantes, 'minutos e', segundos_restantes, 'segundos.')